excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ${PWD}/Pods

disabled_rules:
  - trailing_whitespace
  - line_length
  - statement_position
  - trailing_comma
  
identifier_name:
  excluded: # excluded via string array
  - id
